### ISSUE TITLE
Add Flatpak and Snaps

### ISSUE THREAD

**Issue by madeofpendletonwool** [madeofpendletonwool/PinePods#106]
In addition actions to automate the creation of them on release

**Comment by Siddharth9890** [comment]
hey @madeofpendletonwool i can try this we need the github work flows for snap and flatpak stores right?

**Comment by madeofpendletonwool** [comment]
With functioning Tauri 2.0 this is finally possible and has been accomplished! The first official flatpak and snap package will come with version 0.7.0 See pr #288
