### ISSUE TITLE
Add verification before deleting user

### ISSUE THREAD

**Issue by madeofpendletonwool** [madeofpendletonwool/PinePods#108]
Super easy addition, add additional check via screen pop up to verify before a user is deleted. Currently, hitting delete user just deletes them.

**Comment by rabroldan** [comment]
Can i take try and take this issue?

**Comment by madeofpendletonwool** [comment]
Of course! Search for "# Modify User Stuff" in main.py. The project UI is built with Python Flet, so have a look at their documentation if you aren't familiar already. It's super quick to pick up! Let me know what other details I can provide!

**Comment by rabroldan** [comment]
alright sounds good ill take a look into it now

**Comment by rabroldan** [comment]
hey quick question, jsut trying to avoid bugs. if  the user decided not to proceed with the delition after verification, where do you want me to send them? like back to the home page?

go_homelogin(page): here?

**Comment by rabroldan** [comment]
sample code
```
            else:
                print("Deletion canceled.")
                go_homelogin(page)
```

**Comment by rabroldan** [comment]
hi @madeofpendletonwool kindly please review thanks

**Comment by madeofpendletonwool** [comment]
Comment created here:

https://github.com/madeofpendletonwool/PinePods/pull/111

You should be able to just close the dialog if the user decides to not delete the user.

**Comment by madeofpendletonwool** [comment]
Added in version 0.4
