### ISSUE TITLE
Issue when opening full screen playing and then navigating back to different page

### ISSUE THREAD

**Issue by madeofpendletonwool** [madeofpendletonwool/PinePods#112]
The playing bar at the bottom doesn't reappear. Likely a super quick fix. One liner.

**Comment by mintbomb27** [comment]
Can I work on this?

**Comment by mintbomb27** [comment]
Can I work on this?

**Comment by madeofpendletonwool** [comment]
Of course! Take a look in main.py for this as a start

        if page.route == "/playing" or page.route == "/playing":
            pod_controls.audio_container.visible = False

The issue is when leaving the /playing route. The audio_container is removed from screen when going to this route but when leaving and browsing to a different page it doesn't reappear like it should.

**Comment by madeofpendletonwool** [comment]
This issue is fixed in the next point release coming tomorrow. There was two lines of code causing it to not reappear on redirect. Apologies @mintbomb27, I noticed the issue cause while investigating something else. Didn't mean to steal your thunder.
