### ISSUE TITLE
No notification for episode actions in searching for specific episodes menu

### ISSUE THREAD

**Issue by essys** [madeofpendletonwool/PinePods#129]
I'm trying out PinePods and liking it so far. Thanks for another podcast organiser/player.
I'm trying to get away from Audiobookshelf, which is great but doesn't really fit my way of tracking and listening to podcasts.
I like the simpler approach of PinePods, which also contributes to an overall more smooth listening process.

When I search for specific episodes via "Search Podcasts" menu, the episode options ('Queue Episode', 'Save Episode', 'Download Episode') do not give any notification response to the user.
However, it should be noted that the function still works. Episodes are saved, queued or downloaded, but there's just no visible notification about it, which is a bit irritating.
When I do the same in my 'Home' tab I get expected popups at the bottom of the screen.

In addition, PinePods does not recognise already 'saved' episodes on the search results page:
Home tab:
<img width="1198" alt="Screenshot 2024-04-25 at 10 22 25" src="https://github.com/madeofpendletonwool/PinePods/assets/7117619/98f383ac-19bb-408a-b3dd-e3fd9bd7e383">

Same (already saved) episode via search:
<img width="1196" alt="Screenshot 2024-04-25 at 10 22 53" src="https://github.com/madeofpendletonwool/PinePods/assets/7117619/84636cc1-f9c5-4139-96dd-dcb073fe4918">

**Comment by madeofpendletonwool** [comment]
Thanks for pointing this out! It's these kinds of small interactions all over the place that I am currently trying tidy up to make for a really nice user experience. I've been actively trying to compile a list of all these kinds of things. For example, I just cleaned up an issue with inconsistent scrolling that sometimes happens when you navigate from page to page. Expect a fix for this soon!

**Comment by madeofpendletonwool** [comment]
0.6.2 is releasing now and has a fix for this problem! Closing this issue out. Please feel free to open other issues for other ux/user experience issues if you find them. Now is the time to hammer them all out. Thanks!
