### ISSUE TITLE
Support for GPodder Sync Endpoint

### ISSUE THREAD

**Issue by rgarcia6520** [madeofpendletonwool/PinePods#139]
I use AntennaPod but do not have nextcloud, following some antennapod forum suggestions I was successfully able to deploy and have my antennapod sync to a https://github.com/bohwaz/micro-gpodder-server container. Would enjoy if PinePods can sync/fetch to a generic GPodder endpoint similar to AntennaPod.

**Comment by eliassoares** [comment]
"I am in the same situation as @rgarcia6520."

**Comment by madeofpendletonwool** [comment]
Thanks @eliassoares! I really love the idea and I hadn't realized the micro-gpodder-server container was a project that was maintained. It's certainly in the works. I'd like to get to it this week. Should be really quick and easy to get going considering the majority of work is already done. Hoping to finish up Postgres support first here.

**Comment by madeofpendletonwool** [comment]
![image](https://github.com/madeofpendletonwool/PinePods/assets/22776262/41355198-e0d9-4b70-9d82-fa1d8a55a264)

Just about got this ready to roll! Hoping to have an update out that supports external gpodder clients by the end of the day. Here it is running on my laptop with subscriptions synced from Pinepods!

There's an additional option in the connect podcast sync settings area that includes gpodder compatible servers as an option now. I apologize it's taken awhile. The apis between gpodder sync and the nextcloud implementation actually very a lot. So it was not a drop in feature. I'll add another comment once the new update is out

**Comment by madeofpendletonwool** [comment]
Version 0.6.1 is now out! Which has this in it. Pull down the latest container and feel free to give it a go. I'm going to close this issue. Feel free to open a new one if you have any troubles. Enjoy!
