### ISSUE TITLE
Intelligent Episode action updates throughout the app

### ISSUE THREAD

**Issue by D3an1el** [madeofpendletonwool/PinePods#160]
Once "Download Episode" is clicked it should change to "Remove Downloaded Episode"

Makes it simpler if its under the podcast, not under another tab "Downloads" imo.

**Comment by madeofpendletonwool** [comment]
Changed the title to more generally reflect the issue of buttons not updating based on episode specific status throughout the app. Episode completion status just got added as an option in the dropdown context button and it does update based on the status. So the other options (Queue, Saved, Downloads) need to all function in the same way.

**Comment by madeofpendletonwool** [comment]
Marking as a good first issue due to it being a follow what's already implemented for the others feature

**Comment by madeofpendletonwool** [comment]
All episode interaction buttons now dynamically update throughout the app. This has been added in with #312 and will be added in with version 0.7.0 coming in the next week.
