### ISSUE TITLE
Shows as Downloaded twice when storage has one file

### ISSUE THREAD

**Issue by D3an1el** [madeofpendletonwool/PinePods#161]
Under the podcast if you click "Download Episode"  twice it shows under "Downloads" tab as twice, but only shows its has been downloaded once in the storage folder and you cant delete the episode from "Downloads" tab gives an error. 

![Downloads2](https://github.com/madeofpendletonwool/PinePods/assets/96570135/466756ce-c79c-46ab-a15e-106756c37db2)

Hence the reason i posted enhancement  [add "Remove Downloaded Episode" to Podcast Episode Results](https://github.com/madeofpendletonwool/PinePods/issues/160)

**Comment by madeofpendletonwool** [comment]
Thanks for opening these issues @D3an1el! I'm just finishing up support for postgres and am now moving onto the planned expanding of the features for downloading. I'll take care of these issues as part of that. Expect a fix soon!

**Comment by madeofpendletonwool** [comment]
Hey @D3an1el, a check has now been added to ensure episodes won't get added into the downloads area twice, Give it just a bit here and it'll be pushed to dockerhub. Thanks!
