### ISSUE TITLE
Downloads - possible to download all episodes or have a check mark to select episodes and then download all selected

### ISSUE THREAD

**Issue by jonnyabu1** [madeofpendletonwool/PinePods#164]
There are a couple of podcasts I just started getting to and I found that some earlier episodes were no longer available.  I downloaded what's there now in case more are removed so I will have them available.

But, right now it's a long process of click on each episode and select download.  It'd be cool to have an option to download all, or a selection box you can select the episodes you want ( with a select all option ) and just click Download to get em all at once.  It'd save tons of clicking

**Comment by madeofpendletonwool** [comment]
Good timing! This is what I'm currently working on! I just finished implementing Postgresql support this weekend and now I'm moving into better archival support. Which will include a button to download all on a given podcast. I also have plans for auto downloading when new episodes release. Keep an eye out in the coming days as I polish up version 0.6 which will include this.
