### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by jonnyabu1** [madeofpendletonwool/PinePods#171]
Each time I go to login to the web interface I get a message that my credentials are invalid.  I stop and start the Docker container sometimes once, sometime up to three times, and then it takes my password.  And then it asks me to setup the timezone like it's the first time I logged in.  Odd behavior.

I'm not sure if it's related to 2FA being on or not.  I'm not sure where to look for a message on why it's failing.  The nginx access log just does a get_user, get_key, verify_key over and over.

When it does let me in it continues on to self_service_status, get_theme, and get_time_info?user_id

**Comment by madeofpendletonwool** [comment]
Hi @jonnyabu1, sounds like it could potentially be a database connection issue. Or it isn't able to write to the database. Which db are you using? Mysql or posrgres? Are you using an external db or one build into your pinepods compose file? What browser are you using? Could you share your compose file with the secrets removed? Do you have debugging enabled on the container? That will give more more info. Can you also share the logs when you get the unable to connect error?

Thanks!

**Comment by jonnyabu1** [comment]
Msql

Here's the compose file:
`#version: '3'
services:
  db:
    image: mariadb:latest
    command: --wait_timeout=1800
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: ThePassword
      MYSQL_DATABASE: pypods_database
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_INIT_CONNECT: 'SET @@GLOBAL.max_allowed_packet=64*1024*1024;'
    volumes:
      - /data/pinepods/sql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  pinepods:
    image: madeofpendletonwool/pinepods:latest
    ports:
    # Pinepods Main Port
      - "8040:8040"
    environment:
      # Basic Server Info
      SEARCH_API_URL: 'https://search.pinepods.online/api/search'
      # Default Admin User Information
      USERNAME: user
      PASSWORD: UserPassword
      FULLNAME: Name
      EMAIL: useremail
      # Database Vars
      DB_TYPE: mariadb
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ThePassword
      DB_NAME: pypods_database
      # Enable or Disable Debug Mode for additional Printing
      DEBUG_MODE: False
    volumes:
    # Mount the download and the backup location on the server if you want to. You could mount a nas to the downloads fo
lder or something like that.
    # The backups directory is used if backups are made on the web version on pinepods. When taking backups on the clien
t version it downloads them locally.

      - /data/pinepods/downloads:/opt/pinepods/downloads
      - /data/pinepods/backups:/opt/pinepods/backups
    depends_on:
      - db`
   
Debugging, I don't have on.  I'd have to figure that out - haven't had to do a debug of a container before.

Right now it works.  I had restarted it after I posted this to listen to a podcast so I'm in.  I can see later tonight.  I'm not sure when exactly it breaks but most of the time I'll restart it at work, get in, listen to a podcast or two, then the next day it's not letting me sign in.

**Comment by madeofpendletonwool** [comment]
Oh no problem. Dubugging is built in. Just change your compose file

DEBUG_MODE: False

To

DEBUG_MODE: True

Should make the error much more clear.

**Comment by jonnyabu1** [comment]
Ah duh.  I restarted the container and can't log in.  Looking at the docker logs I see this over and over, which maybe points to an area of issue:

`pinepods-1  | You've selected a mariadb database
pinepods-1  | Client API Server is Starting!
pinepods-1  | Traceback (most recent call last):
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/network.py", line 733, in open_connection
pinepods-1  |     self.sock.connect(sockaddr)
pinepods-1  | OSError: [Errno 113] Host is unreachable
pinepods-1  | 
pinepods-1  | The above exception was the direct cause of the following exception:
pinepods-1  | 
pinepods-1  | Traceback (most recent call last):
pinepods-1  |   File "/pinepods/clients/clientapi.py", line 163, in <module>
pinepods-1  |     connection_pool = setup_connection_pool()
pinepods-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^
pinepods-1  |   File "/pinepods/clients/clientapi.py", line 151, in setup_connection_pool
pinepods-1  |     return pooling.MySQLConnectionPool(
pinepods-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/pooling.py", line 430, in __init__
pinepods-1  |     self.add_connection()
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/pooling.py", line 538, in add_connection
pinepods-1  |     cnx = connect(**self._cnx_config)  # type: ignore[assignment]
pinepods-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/pooling.py", line 294, in connect
pinepods-1  |     return MySQLConnection(*args, **kwargs)
pinepods-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/connection.py", line 169, in __init__
pinepods-1  |     self.connect(**kwargs)
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/abstracts.py", line 1217, in connect
pinepods-1  |     self._open_connection()
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/connection.py", line 575, in _open_connecti
on
pinepods-1  |     self._socket.open_connection()
pinepods-1  |   File "/opt/venv/lib/python3.11/site-packages/mysql/connector/network.py", line 735, in open_connection
pinepods-1  |     raise InterfaceError(
pinepods-1  | mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'db:3306' (113 Host is unrea
chable)
pinepods-1  | 2024-06-14 22:00:30,083 WARN exited: client_api (exit status 1; not expected)`

**Comment by madeofpendletonwool** [comment]
Hmm... The intermittent nature to it makes it challenging. The one thing that would make sense is a timing issue. That, or a problem with the way the db is starting. There is a script that runs prior to the main app that causes it to wait for the database to be available prior to starting the main application. In theory that prevents the issue you're experiencing.

To start with, as long as you don't have a ton of data already saved or anything one easy thing to try would be to completely blow away the directory you have the database saved in. That way you're starting fresh in case the database had something go wrong with it at some point. You also could potentially use the settings to export your podcasts to an opml, blow away the db and then reimport them in settings after you restart from scratch if you want to save all your podcasts you already have added. 

One other thought is perhaps there's another log higher up where the db is erroring. That could tell us why the app can't connect.

Things like directory permissions, incorrect credentials, dns, or firewalls could all cause that error. But I wouldn't expect it to be intermittent. That's the puzzling part to it.

**Comment by jonnyabu1** [comment]
I'll blow it away and redo it this weekend here at some point and see how she goes.  I do have all episodes of several podcasts downloaded, so I suppose one question would be if I just copy those mp3 files off and upload them as is again after rebuilding the system, will it pick those up?  If not, it's super easy now with the download all option so that's not a huge deal

**Comment by jonnyabu1** [comment]
Eh, I did quick delete the sql directory, did a pull, and get the same behavior.  When I get a little more time I'll just blow the whole container away and redo it

**Comment by jonnyabu1** [comment]
I redid the setup but using Postgres as I prefer that.  It would not me let me in, and logs said the database didn't exist.

On a whim I switched to a Debian LXC container ( I use Alma 9 for all my other things including this ) and it let me in.  So far after multiple restarts it's been letting in me with one quirk.  I'll see tomorrow if letting me login fine continues or if if it does like previously after a bit of time.

For the quirk, when I enabled 2fa and sign in now, after putting the code in it gives an error on the page saying "Error setting up time zone."  But if I just hit refresh on the browser it goes on in.  Didn't happen to me until I enabled 2fa.  The Docker log does say:  

`pinepods-1  | Error retrieving MFA secret: 'MFA_Secret'
pinepods-1  | [2024-06-17 07:16:25] [WARNING] - psycopg.pool: rolling back returned connection: <psycopg.Connection [INTRANS] (host=db user=postgres database=pypods_database) at 0x70314ad1cb10>
pinepods-1  | [2024-06-17 07:16:25] [INFO] - uvicorn.access: IPADDR.100:0 - "POST /api/data/verify_mfa HTTP/1.0" 200`


So I would say the original issue could revolve around Alma 9 LXC but I won't know for sure until time has passed.  Seems odd but could be.  

Now that I moved this one to a Debian LXC it has a quirk with 2fa but at least lets me in each time without needing to restart, but I do have to refresh the login page after putting my 2fa code in.  Didn't see any database errors starting up.

I did try to disable 2fa but there's a quirk there where I click the switch thinking it should disable, but then it goes to the setup screen with a QR code.  So instead of disabling 2fa it acts like it wants me to set it up again and won't disable it.

There's another issue after importing the opml file and connecting to my Nextcloud instance, but that's a separate topic

**Comment by madeofpendletonwool** [comment]
Excellent finds @jonnyabu1! Thank you for the extensive testing. There's definitely a couple bugs you've discovered in there. With the Postgres option for db being so new I figured there'd be a few quirks with the implementation to iron out there as well. I'll be back in town from vacation starting tomorrow and get to work right away on a patch to fix up these few newly discovered issues along with the few others found in the other issues that have been opened in the last few days.

**Comment by madeofpendletonwool** [comment]
Hey @jonnyabu1, I just finished up a fix for the disable 2fa bug and also fixed the bug you had with the time zone. I will be releasing a point release in the next day or two here that will include the fixes for those. I'd be curious to know more about that issue you have with the opml file and connecting to nextcloud as that sounds like something that might need a minor fix too. Thanks!

**Comment by jonnyabu1** [comment]
Sweet.  Ty! 

My current status is I had blown the container away again and started from scratch.  I do not have 2fa enabled figuring that'd get fixed down the road.  Once the change is pushed I can enable it and see how she goes.  I do not have a logon issue with the Debian LXC so there could well be something peculiar with Alma that caused some kind of issue talking to the db.  I have not been asked to set my timezone on each login.

For the opml file, I exported 15 feeds.  When I import, like 2 or 3 pull in.  I got 4 imported and subsequent imports didn't add any more feeds.  The only way I got all the feeds in was to go and use the feed URLs in the opml file and add it via Add Custom Feed.  

In my previous container ( before I blew it away ) I added The Homelab Show via the Podcast Index search and it added some wonky feed that only had 10 episodes.  I found the actual feed and added that manually so I had two entries for The Homelab Show.  But I couldn't delete the 10 episode one.  I'd hit delete, but it wouldn't go away.

For Nextcloud, I use it to sync AntennaPod on my phones.  I've noticed in all my instance iterations that when I would go to add my server I would have to add it like 5 times for it to show connected.  But even then I have yet to see anything I've listened to on Pinepods show on my phones as being listened to.  Or show listening status such as a timestamp I left off on.  So basically from what it appears, it's not doing anything by having it connected to the NextCloud 

Perhaps one thing too.  I'm not sure if it's supposed to show that I listened to an episode of a podcast in some visual way but I don't see any way to tell just by looking at the episode list.  I would think it'd get greyed out to look different, or have some visual indicator like a check mark or something to show what I listened to.

I mention that both as a possible feature and that I can't tell if Pinepods is pulling the listening state from Nextcloud.  I know it's not pushing it since AntennaPod shows episodes sort of dimmed out that have been listened to and none that I've listened to on Pinepods has shown in such a state in AP

**Comment by madeofpendletonwool** [comment]
Hi again @jonnyabu1, going through here and fixing up some final bugs before I send out the new release today here. 

Can you expand a bit more on your setup when you say "I use Alma 9 for all my other things including this"? Do you mean you were running Pinepods on an Alma 9 LXC container? And that's what wasn't working? Just ensuring when I test your specific use case I get all the specifics right. 

I pretty tested the opml import today and interestingly I didn't notice any issues on my end. My file was huge too. It had 80 feeds on it. I wonder if the issue you were experiencing was due to there being a feed that the app had an issue with perhaps. Like it perhaps hit that Homelab Show feed and didn't continue on or something like that. 

Nextcloud/Gpodder sync currently syncs podcasts and timestamps. If you have feeds in nextcloud podcast sync and connect Pinepods it will sync all those shows in. Currently, that process takes like 15 or so mins after you add your Nextcloud server for the shows to sync in because it adds them on the next scheduled episode sync. In the very shortterm I'll be improving that so it syncs them in right away. The only thing it doesn't currently sync it episode complete status. Episode complete status is brand new and just got added into the Pinepods about 15 days ago. After completing an episode or manually marking it as complete it will change to look like this now

![image](https://github.com/madeofpendletonwool/PinePods/assets/22776262/06ac3385-aca0-4f2e-b945-6e3993be1b60)

That, doesn't yet sync, but everything else does. Including timestamps from external apps and it also pushes timestamps from Pinepods up. Just doesn't push completion status. Working on getting that to sync soon. 

As for your issue with The Homelab Show. That's an interesting edgecase. I bet it got confused due to the titles being the same. I'm going to create a separate issue for that and take that bug on. Should be fairly easy to fix. Just need to remove pods based on database id rather than title/feeds.

**Comment by jonnyabu1** [comment]
Thanks for all the looking and work!

For me saying I used Alma 9 LXC, so I use Proxmox and in Proxmox you can either spin up a VM, or a LXC container.  Those you just download from within Proxmox.  Since I've used CentOS and now Alma for work for quite some time, I just stuck with that.  But I'm no stranger to Debian so I spun up a Debian LXC container in Proxmox to see if that changed anything and as noted it did seem to somehow make a difference as far as database stuff.  Odd but looks to be the case.

**Comment by madeofpendletonwool** [comment]
Closing this issue and continuing the LXC investigation here: #238
