### ISSUE TITLE
Text overflod on small screens

### ISSUE THREAD

**Issue by SirBogner** [madeofpendletonwool/PinePods#204]
When words in the podcast titles use too much space, the podcast 'card' will not fit the screen. This is shown below.
Also when using the PWA, the area round the navigation knob shows as white.

![Screenshot_20240712_223311_Firefox](https://github.com/user-attachments/assets/0ba0a4a4-0014-4bd5-a8a3-544a54f6b7b7)

**Comment by madeofpendletonwool** [comment]
Thanks for pointing these issues out!

I'm actually currently going back through and fixing up remaining mobile layout issues as I add in podcasting 2.0 support currently so I'll get this cleaned up asap. Check back soon!

**Comment by SirBogner** [comment]
Great! I am really looking forward to PinePods being a good substitution to Google Podcasts. Thank you for the work 😊

**Comment by madeofpendletonwool** [comment]
Version 0.6.3 is out and it should take care of this issue! I actually checked with that podcast specifically and it looks much better now. Things overall scale significantly better. Thanks for opening the issue!
