### ISSUE TITLE
See More Button Displays regardless of the amount of text a description has

### ISSUE THREAD

**Issue by madeofpendletonwool** [madeofpendletonwool/PinePods#205]

**Comment by boc-the-git** [comment]
I came to post just this. The example I'd reference is the `Pinepods News Feed` that has a fairly short description but shows 'See More' on the `BASEURL/podcasts` endpoint.

**Comment by madeofpendletonwool** [comment]
This is on the list to fix for the next minor version! Expect a fix soon

**Comment by madeofpendletonwool** [comment]
This is now fixed out. The descriptions are now expandable by clicking them. So the see more button just no longer exists. Now only does this fix this issue, but it also just cleans up the view a bit.
