### ISSUE TITLE
Lack of a "home" button

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#210]
When on any page of the app, there is no "shortcut" to get to the home page. You need to click the "menu" to then get an option to navigate to home.
Tested on both desktop and mobile, with the same experience.

**Comment by madeofpendletonwool** [comment]
This is a good thought, that kind of quick access shortcut would fit in well I think. I'll get it added for the next minor release to the right of the menu button

**Comment by madeofpendletonwool** [comment]
Added in #244
