### ISSUE TITLE
Feature Request: 'Delete' button on /podcasts should have a confirmation dialog

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#211]
I believe the 'Delete' button on `/podcasts` should have a confirmation dialog so that one wrong click doesn't delete all the data for a podcast.

**Comment by madeofpendletonwool** [comment]
A confirmation has been added in 0.6.3 on the episodes-layout page. I'll get one added on /podcasts as well. Good call

**Comment by madeofpendletonwool** [comment]
This has been added in #247
