### ISSUE TITLE
Feature Request: Podcast OPML Import to display meaningful podcast names

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#212]
Currently the import displays the RSS feed, rather than anything human readable.

![image](https://github.com/user-attachments/assets/9d8c32aa-01de-4305-8c65-4d5c8fb0a090)

**Comment by boc-the-git** [comment]
It looks like the current code is expecting a `title` tag:
https://github.com/madeofpendletonwool/PinePods/blob/19a45b46806c057cd52d79454fc53af538c34530/web/src/components/gen_funcs.rs#L188-L189

Podcast Addict outputs the title of the podcast in the `text` tag.

Very limited research on my part shows that OPML isn't exactly a well defined format..

**Comment by madeofpendletonwool** [comment]
Hi @boc-the-git, the standard for an opml file for podcasts does indeed expect a title. And usually it looks like this in app:

![image](https://github.com/user-attachments/assets/0b973227-2b6b-4c9d-b117-02e986fe6821)


So yeah generally it'll show the title too. Good find with the text tag though. I was unaware sometimes apps put that in that text field. I'll get that updated so it can be either.

**Comment by madeofpendletonwool** [comment]
Got a fix for this completed and it  will roll out with version 0.6.4. It will use title if there otherwise fall back to text.

**Comment by madeofpendletonwool** [comment]
Closing this due to the fix having rolled out in 0.6.4
