### ISSUE TITLE
Log output from database scripts need improved, they're giving false information

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#219]
Take this for instance: 
https://github.com/madeofpendletonwool/PinePods/blob/b098f85b034bb8f333e26c76800f8197fc0475bb/startup/setuppostgresdatabase.py#L136-L151

It tells me on every container start that it has created the table, when in fact it hasn't.

Some other examples (not an exhaustive list!):
https://github.com/madeofpendletonwool/PinePods/blob/b098f85b034bb8f333e26c76800f8197fc0475bb/startup/setuppostgresdatabase.py#L188-L193

https://github.com/madeofpendletonwool/PinePods/blob/b098f85b034bb8f333e26c76800f8197fc0475bb/startup/setuppostgresdatabase.py#L265

https://github.com/madeofpendletonwool/PinePods/blob/b098f85b034bb8f333e26c76800f8197fc0475bb/startup/setuppostgresdatabase.py#L347-L356

**Comment by madeofpendletonwool** [comment]
You're absolutely right. Lot of this is leftover remnants from testing. I went ahead and cleaned it all up. Messaged output from startup should be much more clear now in #232. This will release as part of 0.6.4
