### ISSUE TITLE
"Edit Existing User" doesn't adjust to screen size, impossible to exit

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#220]
When I open 'Edit Existing User', on my default resolution, I can't see the heading bar that includes the X to close. ESC doesn't close it. I end up with no way to close the dialog that is visible to me.
If I zoom out my browser, the heading comes into view and I can exit.

I've got a 2560x1600 resolution with scale 200%.

**Comment by madeofpendletonwool** [comment]
Modals got some functionality bump in #247. You can now click outside them to close them and also they overlap everything in the all, including the app bar now. This should prevent the issues you experienced.
