### ISSUE TITLE
Feature Request: Support podcasts requiring passwords

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#221]
I'm not sure the full extent of what is required here.

In my usecase, I'm after [this podcast](https://www.theanfieldwrap.com/instructions/).
Navigating to their RSS feed at https://www.theanfieldwrap.com/player/subscribe prompts for user/pass.

My assumption is basic auth is what's needed to get access.
(briefly discussed on discord)

**Comment by boc-the-git** [comment]
This is achievable via "add customer feed" in the settings, using a format like `https://user:password@www.theanfieldwrap.com/player/subscribe`, but it's obviously not user friendly

**Comment by madeofpendletonwool** [comment]
0.6.5 is out! This is now fully supported!
https://github.com/madeofpendletonwool/PinePods/releases/tag/0.6.5
