### ISSUE TITLE
Feature Request: Add ability to order the /podcasts page

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#226]
I'd like/expect to be able to arrange the order things appear on the page.

**Comment by madeofpendletonwool** [comment]
What kind of ordering would you like? Sort options? Like alphabetical etc... Is that the idea?

**Comment by boc-the-git** [comment]
Can't remember my exact thoughts at the time..

I want to arrange in the exact order I want. Not a "sort by X" but more a "drag and drop into position", if that makes sense.
A newly added podcast is in last position.

**Comment by madeofpendletonwool** [comment]
These sorting options have been implemented for the podcasts page. For now, this is what I'm going to keep it at

![image](https://github.com/user-attachments/assets/9a2a7b24-9d64-4516-b4ba-4e3398d189e4)
