### ISSUE TITLE
Feature Request: Change the layout of the /podcasts page

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#227]
This could be changing the default or adding other options and allowing someone to set their default..

Currently it's just a long list of things, top to bottom, 1 per row. The ability to have a grid pattern with more condensed information would allow a lot more information on screen at once.

**Comment by madeofpendletonwool** [comment]
Good thought, that's definitely a feasible addition to every page. It's on my list to also add in the option to search for podcast quickly with a little search bar that updates on the fly and also be able to sort them by categories. I'm currently working on adding manually adjustable categories by the user as a component of that

**Comment by boc-the-git** [comment]
Nice, being able to add tags/categories to your podcasts and filter on those is definitely a good idea. You might be in the mood for podcasts of "category X" without wanting a specific podcast.

**Comment by madeofpendletonwool** [comment]
A grid layout has been implemented and will be released in the next 24ish hours in version 0.7.0.
