### ISSUE TITLE
There's a lot of "white space" at the bottom of every page - on mobile or desktop

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#229]
The title basically. I've experienced this on most/every page.. you can keep scrolling for what looks like an additional ~100% of screen height, after the last thing displaying any data.

**Comment by madeofpendletonwool** [comment]
Yeah that's been on my list to deal with for pretty much ever. Thanks for the reminder! It was due to a rough min-h-screen css element. Fixed in #230
