### ISSUE TITLE
The left menu isn't scrollable

### ISSUE THREAD

**Issue by boc-the-git** [madeofpendletonwool/PinePods#258]
When I open developer tools at the bottom of the screen, it covers up a large chunk of the left menu. As it's not scrollable, there's no way for me to bring the lower buttons into view. (The stuff on the main screen other than the left menu _is_ scrollable.)

**Comment by madeofpendletonwool** [comment]
This is fixed in 0.6.6! That update is currently compiling and should be ready to go in about an hour. Thanks for finding that issue
