### ISSUE TITLE
Fresh docker-compose install credentials not working

### ISSUE THREAD

**Issue by xakaitetoia** [madeofpendletonwool/PinePods#267]
Hello,
I have tried the basic example of docker-compose you have in the [documentation](https://www.pinepods.online/docs/intro#compose-file) but I get the error "Your credentials appear to be incorrect". There is something wrong with the mysql setup. I see this in main logs:
```
podcast-pinepods-1  | 2024-08-19 20:52:14,085 - ERROR - Error inserting or updating user: Not all parameters were used in the SQL statement
podcast-pinepods-1  | 2024-08-19 20:52:14,088 - ERROR - Database error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`pypods_database`.`APIKeys`, CONSTRAINT `APIKeys_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE)
```

**Comment by madeofpendletonwool** [comment]
Hi there! I apologize for not getting back sooner. I do have this fixed. And hope to have a fix rolled out in the next day or so as well as a few other things. Apologies, I've been out a bit over the last week dealing with some personal issues.

**Comment by madeofpendletonwool** [comment]
Should be fixed up with the latest update! Docker images are building now so just give it a bit here
https://github.com/madeofpendletonwool/PinePods/releases/tag/0.6.5
