### ISSUE TITLE
Episodes update

### ISSUE THREAD

**Issue by remi64000** [madeofpendletonwool/PinePods#272]
Hello,
When I add a new podcast, the episodes are there but new episodes are not searched.
On my home page, only notes for new Pinepods releases and new episodes of only one of my podcasts are then updated.
Any idea?
Thanks for your amazing work!

**Comment by madeofpendletonwool** [comment]
Hi @remi64000, are you comfortable sharing what the podcast that you're having trouble with is? Issues with specific podcasts at this point are likely to be issues with variations in feeds, and I likely need to implement a check for something that is slightly different in that particular feed. I'm currently working to make the parsing a little more resilient, but to fix that particular podcast I'll need to know how that podcasts feed varies and investigate it specifically. 

Thanks!

**Comment by madeofpendletonwool** [comment]
Perfect! Thanks for letting me know. I've got a huge update coming in the next couple days  with quite a few new features and I'll take a quick look at this issue to see if I can resolve it quickly. Should release as a fix along with the rest of 0.6.6.

**Comment by madeofpendletonwool** [comment]
The new update is currently compiling! Give it about an hour here before pulling I think this will fix your issue. If not, try removing a podcast that has this issue and re-add it again. This should cause it to start working. Let me know if all that doesn't work after upgrading to version 0.6.6 and I'll reopen the issue.

**Comment by remi64000** [comment]
Thanks a lot! I have remove a podcast that has this issue and re-add it again, i will see tonight if it's ok

**Comment by remi64000** [comment]
Hello!
Unfortunately, my podcasts still do not update, despite the update
Have a nice day,

Rémi 

Le 21 sept. 2024, 17:21, à 17:21, Collin Pendleton ***@***.***> a écrit:
