### ISSUE TITLE
Removing Item from the Queue does not work

### ISSUE THREAD

**Issue by pspacekpcty** [madeofpendletonwool/PinePods#274]
STR:
1. Plan any podcast episode to add it into the queue
2. Remove the item from the queue using 3-dots item menu and "Remove from Queue" button

ER:
Item is persistently removed from the queue even after the page is reloaded

AR:
Item is removed from the queue but after the page is reloaded it is back.

**Comment by pspacekpcty** [comment]
Installed version: https://github.com/madeofpendletonwool/PinePods/releases/tag/0.6.5

**Comment by madeofpendletonwool** [comment]
This is fixed in 0.6.6! That update is currently compiling. Should be ready to roll in about an hour. Thanks for reporting the issue!
