### ISSUE TITLE
Add progress of import for OPML

### ISSUE THREAD

**Issue by Else00** [madeofpendletonwool/PinePods#276]
I'm importing a relatively big OPML (150+ podcasts)
I uploaded the file, pressed "Add them!" but there is no progress indication, there is only the wheel spinning in the top left, if i click it nothing appears.
I don't know if i can reload the page and if i reload the page the wheel disappear, so i don't know if the import process is still progressing or if is cancelled.

It's a good idea showing a progressbar for the importing of podcasts and make sure it appear when i reload the page if is still importing.

<img width="1107" alt="Screenshot 2024-09-06 at 11 12 45" src="https://github.com/user-attachments/assets/4b91c46c-5946-4cb3-ae72-5f2000f97e06">

**Comment by madeofpendletonwool** [comment]
Hi @Else00, thanks for the putting in the issue! I have a solution for you :)

In addition to this, you can close the page or move somewhere else while imports occur all the changes happen on the backend. 

![image](https://github.com/user-attachments/assets/93c1d4a0-6f9a-4f86-8cc4-3d725a737972)

Keep an eye out for the next version. This is coming soon!

**Comment by madeofpendletonwool** [comment]
Merged into main here: #298 - I ensured this is stateless as well so that it won't effect kubernetes multi-node deployments. This will be part of a much larger version 0.7.0 release soon
