### ISSUE TITLE
QoL podcast player

### ISSUE THREAD

**Issue by hollisticated-horse** [madeofpendletonwool/PinePods#285]
WIP: there might be some personnal preferences coming through :grin:  

- [x] div .title should be a link, not selectable text. 

![2024-09-24-152913_hyprshot](https://github.com/user-attachments/assets/fa9408f5-ca06-4936-a44d-b4474dfebf7d)

- [x] weird scrub-bar resizing when opening the volume controls (desktop) havn't been able to replicate juste yet ...
- [x] podcast episode image with box-shadown and border-radius ?
_before_
![2024-09-24-151918_hyprshot](https://github.com/user-attachments/assets/dd48d22c-9caa-4588-a8cc-eec849db1752)
_after_
![2024-09-24-151819_hyprshot](https://github.com/user-attachments/assets/d2fcb8ce-3d16-434a-ad84-307ff689d690)

- [x] display show notes below player ?  instead of closing the player ? 
- [x] maybe put the volumer slider on the same line as the rest ? 
and shownotes centered underneath
- [x] keyboard shortcuts to jump ahead and backwards
- [x] player speed slider is bit janky : speed text is selectable, and contrast is not great with the white bar underneath. Maybe move the text indicator in the slider button, make it non-selectable (text selection). Or just put it next to the slider ? 
![2024-09-24-153055_hyprshot](https://github.com/user-attachments/assets/c01c868c-82f0-4120-8391-48601c1e4d49)

**Comment by madeofpendletonwool** [comment]
Hi @hollisticated-horse. Thanks for the detailed issue! I genuinely think all these ideas are phenomenal. I don't pretend to be a great frontend designer myself. It certainly is not my forte lol. So I really do appreciate ideas and feedback on making it better. The other component is just finding time to work on the frontend side. Usually I invest quite a bit of time working through features and designing apis on the backend. So finding the time to go back and work on frontend components can be tough. All these ideas are now on the todo list. That's for sure!

**Comment by hollisticated-horse** [comment]
Honestly, what I find phenomenal is you making PinePods !! Thank you so much. I love seing other places being created to get our podcasts. 

I have a look at making a PR for those kinds of things. Could you point me to relevant areas of code ? And how would you like for people to work on the design of PinePods ?

**Comment by madeofpendletonwool** [comment]
Of course! Pinepods is a project that I truthfully really enjoy, and one that's taught me an unbelievable amount about development. Happy to keep working on it and implementing new things!

Thanks for the interest in helping out! There's a dev guide here:
https://www.pinepods.online/docs/Developing/Developing

What you'll want to do for testing any frontend adjustments is use your existing Pinepods server simultaniously while testing your frontend changes on a local version of the frontend. 

1. So you'll need to pull down a forked version of the repo.
2. Install rust - https://rustup.rs/
3. Install trunk (trunk serves the frontend so you can run it locally) https://trunkrs.dev/
4. And then add the wasm rust compilation target - rustup target add wasm32-unknown-unknown
Finally you just run trunk serve on the web directory. The dev guide goes into that more.


As for relevant areas of the code. What you want to take a look at is the audio.rs file - https://github.com/madeofpendletonwool/PinePods/blob/main/web/src/components/audio.rs

That file contains the component for the audio player, including the minimized  version of the player and the fullscreen version of it. Take a look at lines 890-1075. Those are the lines that define the html for the component itself. Any css styles are then defined in this file - https://github.com/madeofpendletonwool/PinePods/blob/main/web/static/styles.css


Feel free to let me know what other questions you have! Thanks again!

**Comment by madeofpendletonwool** [comment]
Oh - and join the discord server if you haven't. There's a development channel in there where I can answer any quick questions that might come up

https://camo.githubusercontent.com/50b8918dacc25a8c27f0f9f6512cf05385c72d473d26798c156e95f52c9f68c3/68747470733a2f2f646362616467652e76657263656c2e6170702f6170692f7365727665722f624b7a48526134474e63

**Comment by madeofpendletonwool** [comment]
All this has been added directly as you specified and for the volume and playback speed components there's little dropdowns that interact with the page much more smooth now. This should all be much better from a usability standpoint. The exception here is with the shownotes button. I haven't created a component to show them below. I understand what you're thinking of as a reference is Antennapods and the way that handles it. I'm still thinking about exactly how to handle that but a fix for that is coming soon as well. 

These updates will come out with Version 0.7.0. Which is coming around the end of this week. Keep an eye out!

**Comment by madeofpendletonwool** [comment]
Clicking show notes now opens a modal with description information in it. This keeps the player opened and can be quickly closed by clicking out of it. There's also a go to episode button which as before takes you to the episode page itself. That's all these QOL fixes complete!
