### ISSUE TITLE
Developer Documentation Error

### ISSUE THREAD

**Issue by Hoverth** [madeofpendletonwool/PinePods#300]
Hi there,
I was trying out getting a developer environment set up so that I could try playing with the codebase, when I noticed an error in the dev documentation.

The line `sudo docker build -t madeofpendletonwool/pinepods:latest` just spits out an error, I believe it's supposed to be `sudo docker build -t madeofpendletonwool/pinepods:latest .`, as that was what worked for me.

Additionally, clicking the "edit me" button at the bottom of any page on the documentation website leads to a 404, which I'm not sure is intentional or not.

Anyway, thanks for a great piece of software!

**Comment by madeofpendletonwool** [comment]
Hi @Hoverth, thanks for pointing these issues out! I just adjusted both of them and the edit button should work correctly now on the docs site. Feel free to let me know if you run into any other challenges during the development process!
