### ISSUE TITLE
ARM Docker image

### ISSUE THREAD

**Issue by lead0r** [madeofpendletonwool/PinePods#92]
I would like to install pinepods server on a raspberry pi, but of course the Docker image will not work due to amd64/arm64 architecture problems. Is there a way to build the image myself or plans to provide arm images?

**Comment by madeofpendletonwool** [comment]
Hey! Thanks for the request! That's absolutely doable. I have a raspberry pi sitting around so I'll see if I can spin it up and create an ARM specific image for Pinepods and get it uploaded to docker hub,

In the meantime, you can build it yourself if you'd like. The dockerfile in the root of the repo can be manually built just fine and *should* work fine on arm. Though, it's possible there could be a dependency issue. Only one way to find out!

I'll update here once I try it!

**Comment by lead0r** [comment]
I got it up and running: https://hub.docker.com/repository/docker/nevial/pinepods-arm/general
Webui is accessible. Now, I'm struggling with log-in issues, but I doubt that's related to the architecture. I probably made a mistake in my docker compose. I'll open a new issue, if I'm not able to solve it myself

**Comment by lead0r** [comment]
Nevermind, I solved it :)

**Comment by madeofpendletonwool** [comment]
Hey that's great! Did you build it with the regular dockerfile? I'd like to keep the ARM version maintained and currently have actions that run to auto build and push the images upon new release, so if you'd be willing to share those details I'll get it added in. Or you're welcome to add a PR too!

**Comment by lead0r** [comment]
Sure, the only thing I did, was: 
```
docker build https://github.com/madeofpendletonwool/PinePods.git\#main -t pinepods-arm
```

**Comment by lead0r** [comment]
> Hey that's great! Did you build it with the regular dockerfile? I'd like to keep the ARM version maintained and currently have actions that run to auto build and push the images upon new release, so if you'd be willing to share those details I'll get it added in. Or you're welcome to add a PR too!

Did you manage to build ARM images? I just tried to build the current version but have this error at the "pip install  --no-cache-dir -r /requirements.txt" part:

```
145.9 Failed to build cffi
145.9 ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
------
Dockerfile:40
--------------------
  38 |     # Install Python packages
  39 |     COPY --from=builder /app/requirements.txt /
  40 | >>> RUN pip install --no-cache-dir -r /requirements.txt
  41 |
  42 |     # Copy wait-for-it script and give execute permission
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r /requirements.txt" did not complete successfully: exit code: 1
```

I think it is missing libffi in the dockerfile?

**Comment by madeofpendletonwool** [comment]
It's actually in progress currently and coming in the next day or so. Because the program is a compiled program now there needs to be an arm specific build stage. I'll be uploading an arm specific version to docker hub and updating documentation to use arm. Thanks!

**Comment by akshara-tg** [comment]
I too use raspberry pi and eagerly waiting for the ARM image. Please let us know once its uploaded.

**Comment by madeofpendletonwool** [comment]
Hi @akshara-tg, I am working to make progress on the arm image it's just proving somewhat difficult because I don't have the most powerful arm hardware out there. I have a raspberry pi 3 model B available to me and that's about it. Compiling a rust based web application on that isn't exactly the fastest process in the world lol. Nonetheless, rest assured I am working on it, it's just a slow process!

**Comment by madeofpendletonwool** [comment]
I spoke too soon! Just got it running actually. Use tag latest-arm to pull it down. I'm going to test a bit more on my end and then add some documentation to the readme. Seems to be performing great though!

**Comment by madeofpendletonwool** [comment]
Just finalized some automation around the arm image. The arm image is now built into the latest tag. Meaning you should be able to pull latest regardless of whether you're on a raspberry pi (or any 64bit arm device) or on an x86_64 machine. Given that, I'm going to go ahead and close this issue out. Feel free to open a new one if you have an problem with your specific device. That information will be vital for troubleshooting specific issues going forward. I'm interested in further supporting additional cpu architectures in the future I just need the capabilities to build the application on them. That's the challenge. 

Backtracking and supporting 32bit arm devices would be tough. That would require some serious overhaul, and seeing that 32bit is pretty aged at this point I think we need to make 64bit OS a requirement.

Should this project ever receive any kinds of monetary donations of any sort, ensuring I have the hardware to support as many architectures as possible will be my priority. I think risc-v really falls within the spirit of this project and I'd be interested in supporting that given the hardware requirements to do so. 

![image](https://github.com/madeofpendletonwool/PinePods/assets/22776262/37f44b13-6a35-4f7c-95df-8b86900be9a2)
