### ISSUE TITLE
Import opml not working

### ISSUE THREAD

**Issue by lead0r** [madeofpendletonwool/PinePods#94]
I am trying to import my AntennaPod subscriptions, but when I am trying to open the opml-file from within the import dialogue, just nothing happens. Here is what Docker log prints:

```Exception in thread Thread-1173 (__sync_handler):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/flet_core/event_handler.py", line 28, in __sync_handler
    h(r)
  File "/pinepods/main.py", line 4293, in import_pick_result
    tree = ET.parse(active_user.import_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1203, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
Exception in thread Thread-1178 (__sync_handler):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/flet_core/event_handler.py", line 28, in __sync_handler
    h(r)
  File "/pinepods/main.py", line 4293, in import_pick_result
    tree = ET.parse(active_user.import_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1203, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 557, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

As I said, the opml file was exported from AntennaPod and has the following format/starts with these lines:
```
<?xml` version='1.0' encoding='UTF-8' standalone='no' `?>
<opml` version="2.0">
```

**Comment by madeofpendletonwool** [comment]
Hmm.. Interesting, historically I actually tested with Antenna Pod. I recently put everything behind a load balancer inside the container so that it could use just one port. Wonder if that cause a breaking change. I'll test the import functionality again.

**Comment by madeofpendletonwool** [comment]
Hey @lead0r, I took a further look into this. The reason you got this is due to limitations in the flet framework on integrating file uploads via web browser. There's not a great way to do it currently. This functionality works entirely fine on the client edition and in the next version release I'm updating both the web and client versions to reflect these changes. That release will be coming in the next couple days.

**Comment by lead0r** [comment]
Hm, that's unfortunate, because I cannot get the macOS client to run either. Running the "pinepods" file (either by doubleclicking or using the "open" command in a terminal always just opens it in TextEdit. When adding ".app" at the end, macOS just states "cannot open application"

**Comment by madeofpendletonwool** [comment]
Interesting, I just tested myself and see what you mean. My mac testing abilities are admittedly a bit limited as I don't have great access to a modern mac. Github did just introduced the m processor based runners which is amazing though. Should be able to build a version using those on the next release. Nonetheless, when I build version 0.4 I'll test the mac client version prior to publishing to ensure it runs correctly. I manually built one just now and it did work.

**Comment by BadCo-NZ** [comment]
Importing through the desktop client on Fedora Kinoite currently does not work as well.

Process:
* open desktop client
* click `settings`
* scroll down to `import data`
* click `import data`, pop up appears
* click `Import OPML of Podcasts` nothing happens

**Comment by madeofpendletonwool** [comment]
Hmm.. Interesting. My assumption there is something to do with the immutable desktop prevents the files api from bringing up a folder select prompt. Which is what normally happens. Admittedly if I had to guess I'd think that's a limitation with the Flet Framework file picker. I'm spinning up a vm as we speak here though, so I'll give it a try and see if I can get an error message or something.

**Comment by BadCo-NZ** [comment]
I tried running from the terminal and this is the output:

```
❯  pinepods 
ERROR:root:Database error

(flet:10839): Gdk-CRITICAL **: 12:09:46.236: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
Response good!
Response good!
No saved session found
test
Response status code: 200
Response text: {"status":"success","retrieved_id":2}
Response good!
Download status: True
```

**Comment by madeofpendletonwool** [comment]
Hey! Without the new release and complete rebuild of the platform onto rust I believe every issue experienced here will be completely solved. The importing (and entire app for that matter) is now much more robust and significantly faster. Give it a shot! If you have any problems feel free to open a new issue but I'll close this one considering the circumstances! Thanks!
