### ISSUE TITLE
Offline mode for playing locally downloaded episodes

### ISSUE THREAD

**Issue by madeofpendletonwool** [madeofpendletonwool/PinePods#98]
An offline mode is totally doable. Essentially it will revolve around downloads. Whatever downloads that are on the computer it should pull those and display them as options to play. If someone is interested in working this I can provide more information on how the local downloads work

**Comment by Siddharth9890** [comment]
This seems interesting can you provide more information @madeofpendletonwool please?

**Comment by madeofpendletonwool** [comment]
Sure thing! The intention here is that on the client versions of the apps (found in the repo at clients -> linux-app -> pinepods.py. Or the folder for OS of your choice. They are all the same.) it would be great to have an offline listening feature.  Currently the app version requires that you are online and connected to a server to start. Next to the login button, there should be a 'Offline Mode' button created or something along those lines. From there it should bump you into the app download page where it only displays local downloads instead of both server downloads and local downloads like it normally does. So everything to do this already exists other than the button. Just need the logic to only display only the downloaded podcasts rather than both server and local. It'd be great if there was also a button when you're listening in offline mode that let you login in case you come back online.

**Comment by madeofpendletonwool** [comment]
This has been implemented in the client versions of Pinepods for 0.6.2 and will be rolling out as an official release shortly
